### PR TITLE
upgrade eyes.selenium version

### PR DESCRIPTION
**Pull request by jonathanadler**
Required from Applitools:

https://help.applitools.com/hc/en-us/articles/360038739612?mkt_tok=eyJpIjoiTm1FNFpqZzBNamhsT1RBMyIsInQiOiJkWUtneVFRNkV5RTB4NHI2VmxhYUZacWtjNTdWc0hhbDg2SDNYOFgrTjJyek1VTDB5VFhZMGNRXC91VDBZblpcL2RTbGpuNk04cFFhY05VYzQzMnBlXC9Nc2cxV1pPTytJMkFTS1M1QUpOTUk3a0xWWEVubGJPcnV1ODBvZWQwUGs1OSJ9

### CODE REVIEW

**Comment by jonathanadler** [comment]
@shlomitc 
I bumped the version, because I had a problem with the tests (found out after running the tests with the api key)
I'd be happy if you could take a look.

**Comment by jonathanadler** [comment]
@shlomitc 
Note that the tests aren't running in the PR.
But I added a real test, with a real server.

**Comment by shlomitc** [comment]
Let’s make it run on PRs as well

**Comment by jonathanadler** [comment]
> Let’s make it run on PRs as well

We can't since it's a public repo :( 
I'll send you the ticket I opened for this.

**Comment by shlomitc** [comment]
Regardless of CI issues, let's split this into two PRs.
1. add missing test
2. bump version

**Comment by jonathanadler** [comment]
Can I merge?

**Comment by shlomitc** [comment]
Go for it

**Pull request merged**
